batch_size: 16
n_epochs: 5

#Optimizer
optimizer: Adam
optimizer_params: {lr: 0.001, weight_decay: 0.00001}
test_ratio: 0.1

#Model
model_params: {dim_cond: [1,256,256], conv_size_cond: 3,
               dim_cond_out: [3,256,256],
               cond_dropout: 0.0,
               num_cond_layers: 3,
               dim_x: [3,256,256],
               n_blocks: 2,
               clamping: 0.9,
               conv_size: 3,
               layers_per_block: 3, #includes input and output layer, so 1 means no hidden layers
               dropout: 0.0,
               permute_soft: False}

model_name: "default"
load_model: "default_0623_0"
