batch_size: 12
n_epochs: 400

#Optimizer
optimizer: Adam
optimizer_params: {lr: 0.0002, weight_decay: 0.00001}
test_ratio: 0.1

#Model
model_params: {dim_cond: [1,256,256], conv_size_cond: 3,
               dim_cond_out: [3,256,256],
               cond_dropout: 0.3,
               num_cond_layers: 3,
               dim_x: [3,256,256],
               n_blocks: 20,
               conv_size: 3,
               layers_per_block: 4, #includes input and output layer, so 1 means no hidden layers
               dropout_fc: 0,
               permute: "soft",     #random, soft, None
               blocks_per_group:[12, 12, 12, 6],
               clamping_per_group:[1.0, 1.0, 1.0, 0.6],
               kernel_size_per_group:[3, 3, [3, 3, 1, 3, 3, 1, 3, 3, 1, 3, 1, 3]],
               hidden_layers_per_group:[2, 3, 2, 2],
               fc_size: 1024,
               act_norm: "movingavg",
               pretrain_cond: True,
               encoder_sizes: [2, 2, 2, 1],
               decoder_sizes: [1, 2, 2, 2],
}

model_name: "glow_flickr"
load_model: False
architecture: "glow"
add_data: "/home/ubuntu/flickr_data"
prob_data1: 0.01
